[package]
name = "traffic_light"
version = "0.1.0"
authors = ["Jason Huang <jahuang@nine.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
